-- stylua: ignore start

-- Base Neovim highlights. Each entry is one of:
--   - String: role name, resolved against the current palette's spec table.
--   - Table: palette-agnostic spec (links, reverse, literal values).
--
-- Role specs live per-palette in lua/palette/<name>.lua. Many groups share
-- a role: e.g. Keyword/Conditional/Include/Statement + @keyword.* all use
-- `keyword`; Function/@function.* + @lsp.type.method all use `function_`.
-- Plugin-specific highlights live in lua/plugin_highlights.lua.

return {
  -- ─── Base UI ───
  ColorColumn      = "color_column",
  Conceal          = "conceal",
  Cursor           = { reverse = true },
  CursorColumn     = "color_column",
  CursorIM         = { reverse = true },
  CursorLine       = { bg = "none" },
  CursorLineNr     = "cursor_line_nr",
  Debug            = "debug",
  Directory        = "directory",
  EndOfBuffer      = "end_of_buffer",
  ErrorMsg         = "error_msg",
  FoldColumn       = "fold_column",
  Folded           = "folded",
  LineNr           = "line_nr",
  MoreMsg          = "more_msg",
  NonText          = "non_text",
  Normal           = "normal",
  Question         = "question",
  QuickFixLine     = "quickfix_line",
  SignColumn       = "sign_column",
  SpecialKey       = "special_key",
  Terminal         = "normal",
  ToolbarButton    = "toolbar_button",
  ToolbarLine      = "toolbar_line",
  Visual           = "visual",
  VisualNOS        = "visual_nos",
  WarningMsg       = "warning_msg",
  Whitespace       = "whitespace",
  WinSeparator     = "win_separator",
  debugBreakpoint  = "debug_breakpoint",
  debugPC          = "debug_pc",
  iCursor          = { reverse = true },
  lCursor          = { reverse = true },
  vCursor          = { reverse = true },

  -- ─── Diagnostic ───
  DiagnosticError            = "diag_error",
  DiagnosticHint             = "diag_hint",
  DiagnosticInfo             = "diag_info",
  DiagnosticOk               = "diag_ok",
  DiagnosticWarn             = "diag_warn",
  DiagnosticUnderlineError   = "diag_ul_error",
  DiagnosticUnderlineHint    = "diag_ul_hint",
  DiagnosticUnderlineInfo    = "diag_ul_info",
  DiagnosticUnderlineOk      = "diag_ul_ok",
  DiagnosticUnderlineWarn    = "diag_ul_warn",
  DiagnosticVirtualTextError = "diag_vt_error",
  DiagnosticVirtualTextHint  = "diag_vt_hint",
  DiagnosticVirtualTextInfo  = "diag_vt_info",
  DiagnosticVirtualTextOk    = "diag_vt_ok",
  DiagnosticVirtualTextWarn  = "diag_vt_warn",

  -- ─── Diff / VCS ───
  Added         = "added",
  Changed       = "changed",
  DiffAdd       = "diff_add",
  DiffAdded     = "added",
  DiffChange    = "diff_change",
  DiffChanged   = "changed",
  DiffDelete    = "diff_delete",
  DiffDeleted   = "removed",
  DiffFile      = "diff_file",
  DiffIndexLine = "diff_index_line",
  DiffRemoved   = "removed",
  DiffText      = "diff_text",
  Removed       = "removed",

  -- ─── Float / Popup ───
  FloatBorder = "float_border",
  NormalFloat = "normal_float",
  Pmenu       = "pmenu",
  PmenuSbar   = "pmenu_sbar",
  PmenuSel    = "pmenu_sel",
  PmenuThumb  = "pmenu_thumb",
  WildMenu    = "wild_menu",

  -- ─── LSP ───
  LspCodeLens          = "lsp_code_lens",
  LspCodeLensSeparator = "lsp_code_lens_sep",
  LspReferenceRead     = "lsp_ref",
  -- Visible on the current symbol only. mini.cursorword's matchadd still
  -- renders over LSP extmarks on *other* occurrences, so those keep the
  -- cursorword color instead of LspReferenceTarget.
  LspReferenceTarget   = "lsp_ref_target",
  LspReferenceText     = "lsp_ref",
  LspReferenceWrite    = "lsp_ref",

  ["@lsp.type.builtinType"]    = "ts_type_builtin",
  ["@lsp.type.comment"]        = "comment",
  ["@lsp.type.enum"]           = "lsp_enum",
  ["@lsp.type.enumMember"]     = "lsp_enum_member",
  ["@lsp.type.generic"]        = "lsp_generic",
  ["@lsp.type.interface"]      = "lsp_interface",
  ["@lsp.type.keyword"]        = "keyword",
  ["@lsp.type.macro"]          = "lsp_macro_type",
  ["@lsp.type.method"]         = "function_",
  ["@lsp.type.namespace"]      = "lsp_namespace",
  ["@lsp.type.number"]         = "number",
  ["@lsp.type.parameter"]      = "ts_variable_parameter",
  ["@lsp.type.property"]       = "lsp_property",
  ["@lsp.type.typeParameter"]  = "lsp_type_parameter",
  ["@lsp.type.variable"]       = "ts_markup",

  ["@lsp.typemod.function.defaultLibrary"] = "function_",
  ["@lsp.typemod.method.defaultLibrary"]   = "function_",
  ["@lsp.typemod.operator.injected"]       = "ts_markup",
  ["@lsp.typemod.string.injected"]         = "string_",
  ["@lsp.typemod.variable.defaultLibrary"] = "lsp_tm_var_default",
  ["@lsp.typemod.variable.injected"]       = "ts_markup",
  ["@lsp.typemod.variable.static"]         = "lsp_tm_var_static",

  -- ─── Search / Match ───
  CurSearch  = "cur_search",
  IncSearch  = "inc_search",
  MatchParen = "match_paren",
  Search     = "search",
  Substitute = "substitute",

  -- ─── Spell ───
  SpellBad   = "spell_bad",
  SpellCap   = "spell_cap",
  SpellLocal = "spell_local",
  SpellRare  = "spell_rare",

  -- ─── Statusline / Tabline ───
  StatusLine       = "status_line",
  StatusLineNC     = "status_line_nc",
  StatusLineTerm   = "status_line_term",
  StatusLineTermNC = "status_line_term_nc",
  TabLine          = "tab_line",
  TabLineFill      = "tab_line_fill",
  TabLineSel       = "tab_line_sel",

  -- ─── Syntax (vim-native) ───
  Boolean        = "boolean",
  Character      = "character",
  Comment        = "comment",
  Conditional    = "keyword",
  Constant       = "constant",
  Define         = "define",
  Delimiter      = "delimiter",
  Error          = "error_syn",
  Exception      = "keyword",
  Float          = "number",
  Function       = "function_",
  Identifier     = "identifier",
  Include        = "keyword",
  Keyword        = "keyword",
  Label          = "label",
  Macro          = "macro",
  Number         = "number",
  Operator       = "operator",
  PreCondit      = "pre_condit",
  PreProc        = "pre_proc",
  Repeat         = "keyword",
  Special        = "special",
  SpecialChar    = "special_char",
  SpecialComment = "special_comment",
  Statement      = "keyword",
  StorageClass   = "storage_class",
  String         = "string_",
  Structure      = "storage_class",
  Tag            = "tag",
  Title          = "title",
  Todo           = "todo",
  Type           = "type_",
  Typedef        = "storage_class",

  -- ─── Treesitter ───
  ["@annotation"]                       = "ts_markup",
  ["@attribute"]                        = "ts_attribute",
  ["@attribute.typescript"]             = "ts_attribute_ts",
  ["@boolean"]                          = "boolean",
  ["@character"]                        = "ts_character",
  ["@character.special"]                = "ts_character_special",
  ["@comment"]                          = "comment",
  ["@comment.todo"]                     = "todo",
  ["@comment.todo.checked"]             = "ts_comment_checked",
  ["@comment.todo.unchecked"]           = "ts_comment_unchecked",
  ["@constant"]                         = "ts_constant",
  ["@constant.builtin"]                 = "boolean",
  ["@constant.macro"]                   = "ts_constant_macro",
  ["@constructor"]                      = "ts_constructor",
  ["@constructor.lua"]                  = "ts_constructor_lua",
  ["@danger"]                           = "ts_danger",
  ["@diff.add"]                         = "added",
  ["@diff.delete"]                      = "removed",
  ["@diff.delta"]                       = "changed",
  ["@diff.minus"]                       = "removed",
  ["@diff.plus"]                        = "added",
  ["@error"]                            = "ts_error",
  ["@function"]                         = "function_",
  ["@function.builtin"]                 = "ts_function_builtin",
  ["@function.call"]                    = "ts_function_call",
  ["@function.macro"]                   = "ts_function_macro",
  ["@function.method"]                  = "function_",
  ["@function.method.call"]             = "function_",
  ["@keyword"]                          = "keyword",
  ["@keyword.conditional"]              = "keyword",
  ["@keyword.directive"]                = "keyword",
  ["@keyword.exception"]                = "keyword",
  ["@keyword.function"]                 = "keyword",
  ["@keyword.import"]                   = "ts_keyword_import",
  ["@keyword.operator"]                 = "keyword",
  ["@keyword.repeat"]                   = "keyword",
  ["@keyword.return"]                   = "ts_keyword_return",
  ["@label"]                            = "ts_label",
  ["@markup"]                           = "ts_markup",
  ["@markup.emphasis"]                  = "ts_markup_emphasis",
  ["@markup.environment"]               = "ts_markup",
  ["@markup.environment.name"]          = "ts_markup",
  ["@markup.heading"]                   = "ts_markup_heading",
  ["@markup.heading.1.markdown"]        = "ts_markup_heading_red",
  ["@markup.heading.2.markdown"]        = "ts_markup_heading_kw",
  ["@markup.heading.3.markdown"]        = "ts_markup_heading_num",
  ["@markup.heading.4.markdown"]        = "ts_markup_heading_red",
  ["@markup.heading.5.markdown"]        = "ts_markup_heading_kw",
  ["@markup.heading.6.markdown"]        = "ts_markup_heading_num",
  ["@markup.heading.1.marker.markdown"] = "ts_markup_heading_red",
  ["@markup.heading.2.marker.markdown"] = "ts_markup_heading_kw",
  ["@markup.heading.3.marker.markdown"] = "ts_markup_heading_num",
  ["@markup.heading.4.marker.markdown"] = "ts_markup_heading_red",
  ["@markup.heading.5.marker.markdown"] = "ts_markup_heading_kw",
  ["@markup.heading.6.marker.markdown"] = "ts_markup_heading_num",
  ["@markup.italic"]                    = "ts_markup_emphasis",
  ["@markup.link"]                      = "ts_markup_link",
  ["@markup.link.url"]                  = "ts_markup_link_url",
  ["@markup.list"]                      = "ts_markup_list",
  ["@markup.math"]                      = "ts_markup_math",
  ["@markup.quote.markdown"]            = "ts_markup_quote",
  ["@markup.raw"]                       = "ts_markup_raw",
  ["@markup.strike"]                    = "ts_markup_strike",
  ["@markup.strong"]                    = "ts_markup_strong",
  ["@markup.underline"]                 = "ts_markup_underline",
  ["@module"]                           = "ts_module",
  ["@none"]                             = "ts_markup",
  ["@note"]                             = "ts_markup",
  ["@number"]                           = "number",
  ["@number.float"]                     = "number",
  ["@operator"]                         = "ts_operator",
  ["@parameter.reference"]              = "ts_parameter_ref",
  ["@property"]                         = "ts_property",
  ["@punctuation.bracket"]              = "ts_punct",
  ["@punctuation.delimiter"]            = "ts_punct",
  ["@punctuation.special"]              = "ts_punct_special",
  ["@string"]                           = "string_",
  ["@string.escape"]                    = "ts_string_escape",
  ["@string.regexp"]                    = "ts_string_regexp",
  ["@string.special.symbol"]            = "ts_string_symbol",
  ["@string.special.url"]               = "ts_string_url",
  ["@tag"]                              = "ts_tag",
  ["@tag.attribute"]                    = "ts_tag_attribute",
  ["@tag.delimiter"]                    = "ts_tag_delimiter",
  ["@text"]                             = "ts_markup",
  ["@type"]                             = "ts_type",
  ["@type.builtin"]                     = "ts_type_builtin",
  ["@type.declaration"]                 = "ts_type_decl",
  ["@type.definition"]                  = "ts_type_decl",
  ["@variable"]                         = "ts_variable",
  ["@variable.builtin"]                 = "ts_variable_builtin",
  ["@variable.member"]                  = "ts_variable_member",
  ["@variable.parameter"]               = "ts_variable_parameter",
  ["@warning"]                          = "ts_warning",
}
