-- stylua: ignore start
-- original https://github.com/yorickpeterse/nvim-grey
-- Palette role specs. See palette/vague.lua for the role catalog.

local c = {
  background    = "#f2f2f2",
  grey_bg_light = "#ececec",
  black         = "#000000",
  blue          = "#1561b8",
  light_blue    = "#d3e0f2",
  diff_text     = "#a8c2de",
  green         = "#1C5708",
  light_green   = "#dfeacc",
  light_red     = "#f2d3cd",
  red           = "#c4331d",
  grey          = "#5e5e5e",
  light_grey    = "#e6e6e6",
  border        = "#cccccc",
  highlight     = "#e3eaf3",
  dark_yellow   = "#b37f02",
  yellow        = "#f9db70",
  light_yellow  = "#f9eab3",
  orange        = "#a55000",
  purple        = "#5c21a5",
  white         = "#ffffff",
  cyan          = "#007872",
}

return {
  color_column     = { bg = c.highlight },
  conceal          = { fg = c.grey },
  cursor_line_nr   = { fg = c.black, bold = true },
  debug            = { fg = c.dark_yellow },
  directory        = { fg = c.purple },
  end_of_buffer    = { fg = c.background, bg = c.background },
  error_msg        = { fg = c.red, bold = true },
  fold_column      = { fg = c.grey },
  folded           = { fg = c.grey, bg = c.light_grey },
  line_nr          = { fg = c.grey },
  more_msg         = { fg = c.black },
  non_text         = { fg = c.grey },
  normal           = { fg = c.black, bg = c.background },
  question         = { fg = c.black },
  quickfix_line    = { bg = c.highlight, bold = true },
  sign_column      = { fg = c.grey },
  special_key      = { fg = c.blue },
  toolbar_button   = { fg = c.white, bg = c.blue },
  toolbar_line     = { fg = c.black },
  visual           = { bg = c.light_blue },
  visual_nos       = { bg = c.light_blue, underline = true },
  warning_msg      = { fg = c.dark_yellow, bold = true },
  whitespace       = { fg = c.border },
  win_separator    = { fg = c.border },
  debug_breakpoint = { fg = c.white, bg = c.red },
  debug_pc         = { fg = c.white, bg = c.green },

  diag_error     = { fg = c.red, bold = true },
  diag_hint      = { fg = c.grey, bold = true },
  diag_info      = { fg = c.blue, bold = true },
  diag_ok        = { fg = c.green, bold = true },
  diag_warn      = { fg = c.dark_yellow, bold = true },
  diag_ul_error  = { sp = c.red, underline = true },
  diag_ul_hint   = { sp = c.purple, underline = true },
  diag_ul_info   = { sp = c.blue, underline = true },
  diag_ul_ok     = { sp = c.green, underline = true },
  diag_ul_warn   = { sp = c.dark_yellow, underline = true },
  diag_vt_error  = { fg = c.red, bold = true },
  diag_vt_hint   = { fg = c.black, bold = true },
  diag_vt_info   = { fg = c.blue, bold = true },
  diag_vt_ok     = { fg = c.green },
  diag_vt_warn   = { fg = c.dark_yellow, bold = true },

  added           = { fg = c.green },
  changed         = { fg = c.blue },
  removed         = { fg = c.red },
  diff_add        = { bg = c.light_green },
  diff_change     = { bg = c.light_blue },
  diff_delete     = { fg = c.red },
  diff_text       = { bg = c.diff_text },
  diff_file       = { fg = c.black, bold = true },
  diff_index_line = { fg = c.blue },

  float_border = { fg = c.border },
  normal_float = { fg = c.black },
  pmenu        = { fg = c.black, bg = c.grey_bg_light },
  pmenu_sbar   = { bg = c.grey_bg_light },
  pmenu_sel    = { bg = c.light_grey, bold = true },
  pmenu_thumb  = { bg = c.light_grey },
  wild_menu    = { bg = c.light_grey, bold = true },

  lsp_code_lens      = { fg = c.grey, italic = true },
  lsp_code_lens_sep  = { fg = c.grey },
  lsp_ref            = { bg = c.light_grey },
  lsp_ref_target     = { bg = c.highlight },
  lsp_builtin_type   = { fg = c.black, bold = true },
  lsp_comment_type   = { fg = c.grey, italic = true },
  lsp_enum           = { fg = c.black },
  lsp_enum_member    = { fg = c.purple },
  lsp_generic        = { fg = c.black },
  lsp_interface      = { fg = c.black },
  lsp_keyword        = { fg = c.black, bold = true },
  lsp_macro_type     = { fg = c.orange },
  lsp_method         = { fg = c.black },
  lsp_namespace      = { fg = c.black },
  lsp_number         = { fg = c.blue },
  lsp_parameter      = { fg = c.orange },
  lsp_property       = { fg = c.black },
  lsp_type_parameter = { fg = c.black },
  lsp_variable       = { fg = c.black },
  lsp_tm_fn_default  = { fg = c.black },
  lsp_tm_mth_default = { fg = c.black },
  lsp_tm_op_inj      = { fg = c.black },
  lsp_tm_str_inj     = { fg = c.green },
  lsp_tm_var_default = { fg = c.black, bold = true },
  lsp_tm_var_inj     = { fg = c.black },
  lsp_tm_var_static  = { fg = c.black },

  cur_search  = { bg = c.light_yellow },
  inc_search  = { bg = c.light_yellow },
  match_paren = { bold = true },
  search      = { bg = c.light_yellow },
  substitute  = { bg = c.light_green },

  spell_bad   = { sp = c.red, underline = true },
  spell_cap   = { sp = c.dark_yellow, underline = true },
  spell_local = { sp = c.blue, underline = true },
  spell_rare  = { sp = c.purple, underline = true },

  status_line         = { fg = c.black, bg = c.background },
  status_line_nc      = { fg = c.black, bg = c.grey_bg_light },
  status_line_term    = { fg = c.black, bg = c.background },
  status_line_term_nc = { fg = c.black, bg = c.grey_bg_light },
  tab_line            = { fg = c.black, bg = c.light_grey },
  tab_line_fill       = { fg = c.black, bg = c.light_grey },
  tab_line_sel        = { fg = c.black, bg = c.background, bold = true },

  boolean         = { fg = c.black, bold = true },
  character       = { fg = c.green },
  comment         = { fg = c.grey },
  conditional     = { fg = c.black, bold = true },
  constant        = { fg = c.black },
  define          = { fg = c.black, bold = true },
  delimiter       = { fg = c.black },
  error_syn       = { fg = c.red, bold = true },
  exception       = { fg = c.black, bold = true },
  float           = { fg = c.blue },
  function_       = { fg = c.black },
  identifier      = { fg = c.black },
  include         = { fg = c.black, bold = true },
  keyword         = { fg = c.black, bold = true },
  label           = { fg = c.black, bold = true },
  macro           = { fg = c.orange },
  number          = { fg = c.blue },
  operator        = { fg = c.black },
  pre_condit      = { fg = c.orange },
  pre_proc        = { fg = c.black },
  repeat_         = { fg = c.black, bold = true },
  special         = { fg = c.black },
  special_char    = { fg = c.black },
  special_comment = { fg = c.grey },
  statement       = { fg = c.black, bold = true },
  storage_class   = { fg = c.black, bold = true },
  string_         = { fg = c.green },
  structure       = { fg = c.black, bold = true },
  tag             = { fg = c.black, bold = true },
  title           = { fg = c.black, bold = true },
  todo            = { fg = c.grey, bold = true },
  type_           = { fg = c.black },
  typedef         = { fg = c.black, bold = true },

  ts_annotation          = { fg = c.black },
  ts_attribute           = { fg = c.black },
  ts_attribute_ts        = { fg = c.purple },
  ts_boolean             = { fg = c.black, bold = true },
  ts_character           = { fg = c.green },
  ts_character_special   = { fg = c.black },
  ts_comment             = { fg = c.grey },
  ts_comment_todo        = { fg = c.grey, bold = true },
  ts_comment_checked     = { fg = c.green, bold = true },
  ts_comment_unchecked   = { fg = c.red, bold = true },
  ts_constant            = { fg = c.black },
  ts_constant_builtin    = { fg = c.black, bold = true },
  ts_constant_macro      = { fg = c.orange },
  ts_constructor         = { fg = c.black, bold = true },
  ts_constructor_lua     = { fg = c.black },
  ts_danger              = { fg = c.red, bold = true },
  ts_diff_add            = { fg = c.green },
  ts_diff_delete         = { fg = c.red },
  ts_diff_delta          = { fg = c.blue },
  ts_error               = { fg = c.red },
  ts_function            = { fg = c.black },
  ts_function_builtin    = { fg = c.black },
  ts_function_call       = { fg = c.black },
  ts_function_macro      = { fg = c.orange },
  ts_function_method     = { fg = c.black },
  ts_keyword             = { fg = c.black, bold = true },
  ts_keyword_import      = { fg = c.black, bold = true },
  ts_keyword_return      = { fg = c.black, bold = true },
  ts_label               = { fg = c.black, bold = true },
  ts_markup              = { fg = c.black },
  ts_markup_emphasis     = { fg = c.black, italic = true },
  ts_markup_heading      = { fg = c.black, bold = true },
  ts_markup_heading_red  = { fg = c.black, bold = true },
  ts_markup_heading_kw   = { fg = c.black, bold = true },
  ts_markup_heading_num  = { fg = c.black, bold = true },
  ts_markup_link         = { fg = c.blue },
  ts_markup_link_url     = { fg = c.blue, underline = true },
  ts_markup_list         = { fg = c.black, bold = true },
  ts_markup_math         = { fg = c.black },
  ts_markup_quote        = { fg = c.grey },
  ts_markup_raw          = { fg = c.grey },
  ts_markup_strike       = { fg = c.grey, strikethrough = true },
  ts_markup_strong       = { fg = c.black, bold = true },
  ts_markup_underline    = { fg = c.black, underline = true },
  ts_module              = { fg = c.black },
  ts_number              = { fg = c.blue },
  ts_operator            = { fg = c.black },
  ts_parameter_ref       = { fg = c.orange },
  ts_property            = { fg = c.black },
  ts_punct               = { fg = c.black },
  ts_punct_special       = { fg = c.black },
  ts_string              = { fg = c.green },
  ts_string_escape       = { fg = c.orange },
  ts_string_regexp       = { fg = c.orange },
  ts_string_symbol       = { fg = c.orange },
  ts_string_url          = { fg = c.blue },
  ts_tag                 = { fg = c.black, bold = true },
  ts_tag_attribute       = { fg = c.black },
  ts_tag_delimiter       = { fg = c.black },
  ts_type                = { fg = c.black },
  ts_type_builtin        = { fg = c.black, bold = true },
  ts_variable            = { fg = c.black },
  ts_variable_builtin    = { fg = c.black, bold = true },
  ts_variable_member     = { fg = c.purple },
  ts_variable_parameter  = { fg = c.orange },
  ts_warning             = { fg = c.dark_yellow },

  harpoon_border       = { fg = c.border },
  harpoon_window       = { fg = c.black },
  ts_context           = { bg = c.grey_bg_light },
  ts_context_bottom    = { bg = c.grey_bg_light, sp = c.black, underline = true },
  mini_files_border    = { fg = c.border },
  mini_files_modified  = { fg = c.dark_yellow },
  mini_files_normal    = { fg = c.black },
  telescope_border        = { fg = c.border },
  telescope_prompt_border = { fg = c.border },
  telescope_matching   = { fg = c.dark_yellow, bold = true },
  telescope_selection  = { bg = c.light_grey, bold = true },
  telescope_caret      = { fg = c.black, bold = true },
  blink_source         = { fg = c.border, italic = true },
  blink_menu_selection = { link = "PmenuSel" },
  snacks_indent        = { fg = c.border },
  snacks_indent1       = { fg = c.black },
  blink_kind = {
    Default = c.black, Array = c.black, Boolean = c.black,
    Class = c.black, Color = c.green, Constant = c.black,
    Constructor = c.black, Enum = c.black, EnumMember = c.purple,
    Event = c.orange, Field = c.black, File = c.blue,
    Folder = c.purple, Function = c.black, Interface = c.black,
    Key = c.black, Keyword = c.black, Method = c.black,
    Module = c.black, Namespace = c.black, Null = c.grey,
    Number = c.blue, Object = c.black, Operator = c.black,
    Package = c.black, Property = c.black, Reference = c.orange,
    Snippet = c.orange, String = c.green, Struct = c.black,
    Text = c.grey, TypeParameter = c.black, Unit = c.green,
    Value = c.blue, Variable = c.black,
  },
}
