-- stylua: ignore start
-- Palette role specs. See palette/vague.lua for the role catalog.

local c = {
  black       = "#0e1013",
  bg0         = "#1f2329",
  bg1         = "#282c34",
  bg2         = "#30363f",
  bg3         = "#383d4d",
  bg_d        = "#181b20",
  bg_hl       = "#323641",
  bg_blue     = "#61afef",
  bg_yellow   = "#e8c88c",
  fg          = "#a0a8b7",
  purple      = "#bf68d9",
  green       = "#8ebd6b",
  orange      = "#cc9057",
  blue        = "#4fa6ed",
  yellow      = "#e2b86b",
  cyan        = "#48b0bd",
  red         = "#e55561",
  grey        = "#535965",
  light_grey  = "#7a818e",
  dark_cyan   = "#266269",
  dark_red    = "#8b3434",
  dark_yellow = "#835d1a",
  dark_purple = "#7e3992",
  diff_add    = "#272e23",
  diff_delete = "#2d2223",
  diff_change = "#172a3a",
  diff_text   = "#274964",
}

return {
  -- ─── Base UI ───
  color_column     = { bg = c.bg1 },
  conceal          = { fg = c.grey },
  cursor_line_nr   = { fg = c.fg },
  debug            = { fg = c.yellow },
  directory        = { fg = c.blue },
  end_of_buffer    = { fg = c.bg0, bg = c.bg0 },
  error_msg        = { fg = c.red, bold = true },
  fold_column      = { fg = c.fg, bg = c.bg1 },
  folded           = { fg = c.fg, bg = c.bg1 },
  line_nr          = { fg = c.grey },
  more_msg         = { fg = c.blue, bold = true },
  non_text         = { fg = c.grey },
  normal           = { fg = c.fg, bg = c.bg0 },
  question         = { fg = c.yellow },
  quickfix_line    = { fg = c.blue, underline = true },
  sign_column      = { fg = c.fg, bg = c.bg0 },
  special_key      = { fg = c.grey },
  toolbar_button   = { fg = c.bg0, bg = c.bg_blue },
  toolbar_line     = { fg = c.fg },
  visual           = { bg = c.bg3 },
  visual_nos       = { fg = "none", bg = c.bg2, underline = true },
  warning_msg      = { fg = c.yellow, bold = true },
  whitespace       = { fg = c.grey },
  win_separator    = { fg = c.bg3 },
  debug_breakpoint = { fg = c.bg0, bg = c.red },
  debug_pc         = { fg = c.bg0, bg = c.green },

  -- ─── Diagnostic ───
  diag_error    = { fg = c.red },
  diag_hint     = { fg = c.purple },
  diag_info     = { fg = c.cyan },
  diag_ok       = { fg = c.green },
  diag_warn     = { fg = c.yellow },
  diag_ul_error = { sp = c.red, undercurl = true },
  diag_ul_hint  = { sp = c.purple, undercurl = true },
  diag_ul_info  = { sp = c.blue, undercurl = true },
  diag_ul_ok    = { sp = c.green, undercurl = true },
  diag_ul_warn  = { sp = c.yellow, undercurl = true },
  diag_vt_error = { bg = "none", fg = c.dark_red },
  diag_vt_hint  = { bg = "none", fg = c.dark_purple },
  diag_vt_info  = { bg = "none", fg = c.dark_cyan },
  diag_vt_ok    = { bg = "none", fg = c.green },
  diag_vt_warn  = { bg = "none", fg = c.dark_yellow },

  -- ─── Diff / VCS ───
  added           = { fg = c.green },
  changed         = { fg = c.blue },
  removed         = { fg = c.red },
  diff_add        = { fg = "none", bg = c.diff_add },
  diff_change     = { fg = "none", bg = c.diff_change },
  diff_delete     = { fg = "none", bg = c.diff_delete },
  diff_text       = { fg = "none", bg = c.diff_text },
  diff_file       = { fg = c.cyan },
  diff_index_line = { fg = c.grey },

  -- ─── Float / Popup ───
  float_border = { fg = c.fg, bg = "none" },
  normal_float = { fg = c.fg, bg = c.bg0 },
  pmenu        = { fg = c.fg, bg = c.bg1 },
  pmenu_sbar   = { fg = "none", bg = c.bg1 },
  pmenu_sel    = { fg = c.bg0, bg = c.bg_blue },
  pmenu_thumb  = { fg = "none", bg = c.grey },
  wild_menu    = { fg = c.bg0, bg = c.blue },

  -- ─── LSP ───
  lsp_code_lens      = { fg = c.grey, italic = true },
  lsp_code_lens_sep  = { fg = c.grey },
  lsp_ref            = { bg = c.bg2 },
  lsp_ref_target     = { bg = c.diff_text },
  lsp_enum           = { fg = c.yellow },
  lsp_enum_member    = { fg = c.orange },
  lsp_generic        = { fg = c.fg },
  lsp_interface      = { fg = c.yellow },
  lsp_macro_type     = { fg = c.cyan },
  lsp_namespace      = { fg = c.yellow },
  lsp_property       = { fg = c.cyan },
  lsp_type_parameter = { fg = c.yellow },
  lsp_tm_var_default = { fg = c.red },
  lsp_tm_var_static  = { fg = c.orange },

  -- ─── Search / Match ───
  cur_search  = { fg = c.bg0, bg = c.orange },
  inc_search  = { fg = c.bg0, bg = c.orange },
  match_paren = { fg = "none", bg = c.grey },
  search      = { fg = c.bg0, bg = c.bg_yellow },
  substitute  = { fg = c.bg0, bg = c.green },

  -- ─── Spell ───
  spell_bad   = { fg = "none", undercurl = true, sp = c.red },
  spell_cap   = { fg = "none", undercurl = true, sp = c.yellow },
  spell_local = { fg = "none", undercurl = true, sp = c.blue },
  spell_rare  = { fg = "none", undercurl = true, sp = c.purple },

  -- ─── Statusline / Tabline ───
  status_line         = { fg = c.fg, bg = c.bg2 },
  status_line_nc      = { fg = c.grey, bg = c.bg1 },
  status_line_term    = { fg = c.fg, bg = c.bg2 },
  status_line_term_nc = { fg = c.grey, bg = c.bg1 },
  tab_line            = { fg = c.fg, bg = c.bg1 },
  tab_line_fill       = { fg = c.grey, bg = c.bg1 },
  tab_line_sel        = { fg = c.bg0, bg = c.fg },

  -- ─── Syntax + Treesitter (merged) ───
  boolean         = { fg = c.orange },
  character       = { fg = c.orange },
  comment         = { fg = c.grey, italic = true },
  constant        = { fg = c.cyan },
  define          = { fg = c.purple },
  delimiter       = { fg = c.light_grey },
  error_syn       = { fg = c.purple },
  function_       = { fg = c.blue },
  identifier      = { fg = c.red },
  keyword         = { fg = c.purple },
  label           = { fg = c.red },
  macro           = { fg = c.red },
  number          = { fg = c.orange },
  operator        = { fg = c.purple },
  pre_condit      = { fg = c.purple },
  pre_proc        = { fg = c.purple },
  special         = { fg = c.red },
  special_char    = { fg = c.red },
  special_comment = { fg = c.grey, italic = true },
  storage_class   = { fg = c.yellow },
  string_         = { fg = c.green },
  tag             = { fg = c.green },
  title           = { fg = c.cyan },
  todo            = { fg = c.red, italic = true },
  type_           = { fg = c.yellow },

  ts_attribute          = { fg = c.cyan },
  ts_attribute_ts       = { fg = c.blue },
  ts_character          = { fg = c.orange },
  ts_character_special  = { fg = c.red },
  ts_comment_checked    = { fg = c.green, italic = true },
  ts_comment_unchecked  = { fg = c.red, italic = true },
  ts_constant           = { fg = c.orange },
  ts_constant_macro     = { fg = c.orange },
  ts_constructor        = { fg = c.yellow, bold = true },
  ts_constructor_lua    = { fg = c.light_grey },
  ts_danger             = { fg = c.fg },
  ts_error              = { fg = c.fg },
  ts_function_builtin   = { fg = c.cyan },
  ts_function_call      = { fg = c.blue },
  ts_function_macro     = { fg = c.cyan },
  ts_keyword_import     = { fg = c.purple },
  ts_keyword_return     = { fg = c.purple },
  ts_label              = { fg = c.red },
  ts_markup             = { fg = c.fg },
  ts_markup_emphasis    = { fg = c.fg, italic = true },
  ts_markup_heading     = { fg = c.orange, bold = true },
  ts_markup_heading_red = { fg = c.red, bold = true },
  ts_markup_heading_kw  = { fg = c.purple, bold = true },
  ts_markup_heading_num = { fg = c.orange, bold = true },
  ts_markup_link        = { fg = c.blue },
  ts_markup_link_url    = { fg = c.cyan, underline = true },
  ts_markup_list        = { fg = c.red },
  ts_markup_math        = { fg = c.fg },
  ts_markup_quote       = { fg = c.grey },
  ts_markup_raw         = { fg = c.green },
  ts_markup_strike      = { fg = c.fg, strikethrough = true },
  ts_markup_strong      = { fg = c.fg, bold = true },
  ts_markup_underline   = { fg = c.fg, underline = true },
  ts_module             = { fg = c.yellow },
  ts_operator           = { fg = c.fg },
  ts_parameter_ref      = { fg = c.fg },
  ts_property           = { fg = c.cyan },
  ts_punct              = { fg = c.light_grey },
  ts_punct_special      = { fg = c.red },
  ts_string_escape      = { fg = c.red },
  ts_string_regexp      = { fg = c.orange },
  ts_string_symbol      = { fg = c.cyan },
  ts_string_url         = { fg = c.cyan, underline = true },
  ts_tag                = { fg = c.purple },
  ts_tag_attribute      = { fg = c.yellow },
  ts_tag_delimiter      = { fg = c.purple },
  ts_type               = { fg = c.yellow },
  ts_type_builtin       = { fg = c.orange },
  ts_type_decl          = { fg = c.yellow },
  ts_variable           = { fg = c.fg },
  ts_variable_builtin   = { fg = c.red },
  ts_variable_member    = { fg = c.cyan },
  ts_variable_parameter = { fg = c.red },
  ts_warning            = { fg = c.fg },

  -- ─── Plugin highlights ───
  harpoon_border          = { fg = c.cyan },
  harpoon_window          = { fg = c.fg },
  ts_context              = { bg = c.bg0 },
  ts_context_bottom       = { bg = c.bg0, sp = c.fg, underline = true },
  mini_files_border       = { fg = c.cyan },
  mini_files_modified     = { fg = c.yellow },
  mini_files_normal       = { fg = c.fg },
  telescope_border        = { fg = c.red },
  telescope_prompt_border = { fg = c.cyan },
  telescope_matching      = { fg = c.orange, bold = true },
  telescope_selection     = { bg = c.bg2 },
  telescope_caret         = { fg = c.yellow },
  blink_source            = { fg = c.bg3, italic = true },
  blink_menu_selection    = { link = "PmenuSel" },
  snacks_indent           = { link = "NonText" },
  snacks_indent1          = { link = "DiagnosticInfo" },
  xml_tag_name            = { link = "Function" },
  blink_kind = {
    Default = c.purple, Array = c.yellow, Boolean = c.orange,
    Class = c.yellow, Color = c.green, Constant = c.orange,
    Constructor = c.blue, Enum = c.purple, EnumMember = c.yellow,
    Event = c.yellow, Field = c.purple, File = c.blue,
    Folder = c.orange, Function = c.blue, Interface = c.green,
    Key = c.cyan, Keyword = c.cyan, Method = c.blue,
    Module = c.orange, Namespace = c.red, Null = c.grey,
    Number = c.orange, Object = c.red, Operator = c.red,
    Package = c.yellow, Property = c.cyan, Reference = c.orange,
    Snippet = c.red, String = c.green, Struct = c.purple,
    Text = c.light_grey, TypeParameter = c.red, Unit = c.green,
    Value = c.orange, Variable = c.purple,
  },
}
