-- stylua: ignore start
-- Palette role specs. Uses the same spec structure as onedark with light
-- color values. See palette/vague.lua for the role catalog.

local c = {
  black       = "#101012",
  bg0         = "#fafafa",
  bg1         = "#f0f0f0",
  bg2         = "#e6e6e6",
  bg3         = "#dcdcdc",
  bg_d        = "#c9c9c9",
  bg_hl       = "#f0f0f0",
  bg_blue     = "#68aee8",
  bg_yellow   = "#e2c792",
  fg          = "#383a42",
  purple      = "#a626a4",
  green       = "#50a14f",
  orange      = "#c18401",
  blue        = "#4078f2",
  yellow      = "#986801",
  cyan        = "#0184bc",
  red         = "#e45649",
  grey        = "#a0a1a7",
  light_grey  = "#818387",
  dark_cyan   = "#2b5d63",
  dark_red    = "#833b3b",
  dark_yellow = "#7c5c20",
  dark_purple = "#79428a",
  diff_add    = "#e2fbe4",
  diff_delete = "#fce2e5",
  diff_change = "#e2ecfb",
  diff_text   = "#cad3e0",
}

return {
  color_column     = { bg = c.bg1 },
  conceal          = { fg = c.grey },
  cursor_line_nr   = { fg = c.fg },
  debug            = { fg = c.yellow },
  directory        = { fg = c.blue },
  end_of_buffer    = { fg = c.bg0, bg = c.bg0 },
  error_msg        = { fg = c.red, bold = true },
  fold_column      = { fg = c.fg, bg = c.bg1 },
  folded           = { fg = c.fg, bg = c.bg1 },
  line_nr          = { fg = c.grey },
  more_msg         = { fg = c.blue, bold = true },
  non_text         = { fg = c.grey },
  normal           = { fg = c.fg, bg = c.bg0 },
  question         = { fg = c.yellow },
  quickfix_line    = { fg = c.blue, underline = true },
  sign_column      = { fg = c.fg, bg = c.bg0 },
  special_key      = { fg = c.grey },
  toolbar_button   = { fg = c.bg0, bg = c.bg_blue },
  toolbar_line     = { fg = c.fg },
  visual           = { bg = c.bg3 },
  visual_nos       = { fg = "none", bg = c.bg2, underline = true },
  warning_msg      = { fg = c.yellow, bold = true },
  whitespace       = { fg = c.grey },
  win_separator    = { fg = c.bg3 },
  debug_breakpoint = { fg = c.bg0, bg = c.red },
  debug_pc         = { fg = c.bg0, bg = c.green },

  diag_error     = { fg = c.red },
  diag_hint      = { fg = c.purple },
  diag_info      = { fg = c.cyan },
  diag_ok        = { fg = c.green },
  diag_warn      = { fg = c.yellow },
  diag_ul_error  = { sp = c.red, undercurl = true },
  diag_ul_hint   = { sp = c.purple, undercurl = true },
  diag_ul_info   = { sp = c.blue, undercurl = true },
  diag_ul_ok     = { sp = c.green, undercurl = true },
  diag_ul_warn   = { sp = c.yellow, undercurl = true },
  diag_vt_error  = { bg = "none", fg = c.dark_red },
  diag_vt_hint   = { bg = "none", fg = c.dark_purple },
  diag_vt_info   = { bg = "none", fg = c.dark_cyan },
  diag_vt_ok     = { bg = "none", fg = c.green },
  diag_vt_warn   = { bg = "none", fg = c.dark_yellow },

  added           = { fg = c.green },
  changed         = { fg = c.blue },
  removed         = { fg = c.red },
  diff_add        = { fg = "none", bg = c.diff_add },
  diff_change     = { fg = "none", bg = c.diff_change },
  diff_delete     = { fg = "none", bg = c.diff_delete },
  diff_text       = { fg = "none", bg = c.diff_text },
  diff_file       = { fg = c.cyan },
  diff_index_line = { fg = c.grey },

  float_border = { fg = c.fg, bg = "none" },
  normal_float = { fg = c.fg, bg = c.bg0 },
  pmenu        = { fg = c.fg, bg = c.bg1 },
  pmenu_sbar   = { fg = "none", bg = c.bg1 },
  pmenu_sel    = { fg = c.bg0, bg = c.bg_blue },
  pmenu_thumb  = { fg = "none", bg = c.grey },
  wild_menu    = { fg = c.bg0, bg = c.blue },

  lsp_code_lens      = { fg = c.grey, italic = true },
  lsp_code_lens_sep  = { fg = c.grey },
  lsp_ref            = { bg = c.bg2 },
  lsp_ref_target     = { bg = c.diff_text },
  lsp_builtin_type   = { fg = c.orange },
  lsp_comment_type   = { fg = c.grey, italic = true },
  lsp_enum           = { fg = c.yellow },
  lsp_enum_member    = { fg = c.orange },
  lsp_generic        = { fg = c.fg },
  lsp_interface      = { fg = c.yellow },
  lsp_keyword        = { fg = c.purple },
  lsp_macro_type     = { fg = c.cyan },
  lsp_method         = { fg = c.blue },
  lsp_namespace      = { fg = c.yellow },
  lsp_number         = { fg = c.orange },
  lsp_parameter      = { fg = c.red },
  lsp_property       = { fg = c.cyan },
  lsp_type_parameter = { fg = c.yellow },
  lsp_variable       = { fg = c.fg },
  lsp_tm_fn_default  = { fg = c.blue },
  lsp_tm_mth_default = { fg = c.blue },
  lsp_tm_op_inj      = { fg = c.fg },
  lsp_tm_str_inj     = { fg = c.green },
  lsp_tm_var_default = { fg = c.red },
  lsp_tm_var_inj     = { fg = c.fg },
  lsp_tm_var_static  = { fg = c.orange },

  cur_search  = { fg = c.bg0, bg = c.orange },
  inc_search  = { fg = c.bg0, bg = c.orange },
  match_paren = { fg = "none", bg = c.grey },
  search      = { fg = c.bg0, bg = c.bg_yellow },
  substitute  = { fg = c.bg0, bg = c.green },

  spell_bad   = { fg = "none", undercurl = true, sp = c.red },
  spell_cap   = { fg = "none", undercurl = true, sp = c.yellow },
  spell_local = { fg = "none", undercurl = true, sp = c.blue },
  spell_rare  = { fg = "none", undercurl = true, sp = c.purple },

  status_line         = { fg = c.fg, bg = c.bg2 },
  status_line_nc      = { fg = c.grey, bg = c.bg1 },
  status_line_term    = { fg = c.fg, bg = c.bg2 },
  status_line_term_nc = { fg = c.grey, bg = c.bg1 },
  tab_line            = { fg = c.fg, bg = c.bg1 },
  tab_line_fill       = { fg = c.grey, bg = c.bg1 },
  tab_line_sel        = { fg = c.bg0, bg = c.fg },

  boolean         = { fg = c.orange },
  character       = { fg = c.orange },
  comment         = { fg = c.grey, italic = true },
  conditional     = { fg = c.purple },
  constant        = { fg = c.cyan },
  define          = { fg = c.purple },
  delimiter       = { fg = c.light_grey },
  error_syn       = { fg = c.purple },
  exception       = { fg = c.purple },
  float           = { fg = c.orange },
  function_       = { fg = c.blue },
  identifier      = { fg = c.red },
  include         = { fg = c.purple },
  keyword         = { fg = c.purple },
  label           = { fg = c.purple },
  macro           = { fg = c.red },
  number          = { fg = c.orange },
  operator        = { fg = c.purple },
  pre_condit      = { fg = c.purple },
  pre_proc        = { fg = c.purple },
  repeat_         = { fg = c.purple },
  special         = { fg = c.red },
  special_char    = { fg = c.red },
  special_comment = { fg = c.grey, italic = true },
  statement       = { fg = c.purple },
  storage_class   = { fg = c.yellow },
  string_         = { fg = c.green },
  structure       = { fg = c.yellow },
  tag             = { fg = c.green },
  title           = { fg = c.cyan },
  todo            = { fg = c.red, italic = true },
  type_           = { fg = c.yellow },
  typedef         = { fg = c.yellow },

  ts_annotation          = { fg = c.fg },
  ts_attribute           = { fg = c.cyan },
  ts_attribute_ts        = { fg = c.blue },
  ts_boolean             = { fg = c.orange },
  ts_character           = { fg = c.orange },
  ts_character_special   = { fg = c.red },
  ts_comment             = { fg = c.grey, italic = true },
  ts_comment_todo        = { fg = c.red, italic = true },
  ts_comment_checked     = { fg = c.green, italic = true },
  ts_comment_unchecked   = { fg = c.red, italic = true },
  ts_constant            = { fg = c.orange },
  ts_constant_builtin    = { fg = c.orange },
  ts_constant_macro      = { fg = c.orange },
  ts_constructor         = { fg = c.yellow, bold = true },
  ts_constructor_lua     = { fg = c.light_grey },
  ts_danger              = { fg = c.fg },
  ts_diff_add            = { fg = c.green },
  ts_diff_delete         = { fg = c.red },
  ts_diff_delta          = { fg = c.blue },
  ts_error               = { fg = c.fg },
  ts_function            = { fg = c.blue },
  ts_function_builtin    = { fg = c.cyan },
  ts_function_call       = { fg = c.blue },
  ts_function_macro      = { fg = c.cyan },
  ts_function_method     = { fg = c.blue },
  ts_keyword             = { fg = c.purple },
  ts_keyword_import      = { fg = c.purple },
  ts_keyword_return      = { fg = c.purple },
  ts_label               = { fg = c.red },
  ts_markup              = { fg = c.fg },
  ts_markup_emphasis     = { fg = c.fg, italic = true },
  ts_markup_heading      = { fg = c.orange, bold = true },
  ts_markup_heading_red  = { fg = c.red, bold = true },
  ts_markup_heading_kw   = { fg = c.purple, bold = true },
  ts_markup_heading_num  = { fg = c.orange, bold = true },
  ts_markup_link         = { fg = c.blue },
  ts_markup_link_url     = { fg = c.cyan, underline = true },
  ts_markup_list         = { fg = c.red },
  ts_markup_math         = { fg = c.fg },
  ts_markup_quote        = { fg = c.grey },
  ts_markup_raw          = { fg = c.green },
  ts_markup_strike       = { fg = c.fg, strikethrough = true },
  ts_markup_strong       = { fg = c.fg, bold = true },
  ts_markup_underline    = { fg = c.fg, underline = true },
  ts_module              = { fg = c.yellow },
  ts_number              = { fg = c.orange },
  ts_operator            = { fg = c.fg },
  ts_parameter_ref       = { fg = c.fg },
  ts_property            = { fg = c.cyan },
  ts_punct               = { fg = c.light_grey },
  ts_punct_special       = { fg = c.red },
  ts_string              = { fg = c.green },
  ts_string_escape       = { fg = c.red },
  ts_string_regexp       = { fg = c.orange },
  ts_string_symbol       = { fg = c.cyan },
  ts_string_url          = { fg = c.cyan, underline = true },
  ts_tag                 = { fg = c.purple },
  ts_tag_attribute       = { fg = c.yellow },
  ts_tag_delimiter       = { fg = c.purple },
  ts_type                = { fg = c.yellow },
  ts_type_builtin        = { fg = c.orange },
  ts_variable            = { fg = c.fg },
  ts_variable_builtin    = { fg = c.red },
  ts_variable_member     = { fg = c.cyan },
  ts_variable_parameter  = { fg = c.red },
  ts_warning             = { fg = c.fg },

  harpoon_border       = { fg = c.cyan },
  harpoon_window       = { fg = c.fg },
  ts_context           = { bg = c.bg0 },
  ts_context_bottom    = { bg = c.bg0, sp = c.fg, underline = true },
  mini_files_border    = { fg = c.cyan },
  mini_files_modified  = { fg = c.yellow },
  mini_files_normal    = { fg = c.fg },
  telescope_border        = { fg = c.red },
  telescope_prompt_border = { fg = c.cyan },
  telescope_matching   = { fg = c.orange, bold = true },
  telescope_selection  = { bg = c.bg2 },
  telescope_caret      = { fg = c.yellow },
  blink_source         = { fg = c.bg3, italic = true },
  blink_menu_selection = { link = "PmenuSel" },
  snacks_indent        = { link = "NonText" },
  snacks_indent1       = { link = "DiagnosticInfo" },
  blink_kind = {
    Default = c.purple, Array = c.yellow, Boolean = c.orange,
    Class = c.yellow, Color = c.green, Constant = c.orange,
    Constructor = c.blue, Enum = c.purple, EnumMember = c.yellow,
    Event = c.yellow, Field = c.purple, File = c.blue,
    Folder = c.orange, Function = c.blue, Interface = c.green,
    Key = c.cyan, Keyword = c.cyan, Method = c.blue,
    Module = c.orange, Namespace = c.red, Null = c.grey,
    Number = c.orange, Object = c.red, Operator = c.red,
    Package = c.yellow, Property = c.cyan, Reference = c.orange,
    Snippet = c.red, String = c.green, Struct = c.purple,
    Text = c.light_grey, TypeParameter = c.red, Unit = c.green,
    Value = c.orange, Variable = c.purple,
  },
}
